defaults:
  - env/libero_object@env.train
  - env/libero_object@env.eval
  - model/smolvla@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 3
    env,rollout: 2

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_smolvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  eval_policy_path: null # /home/bao_zonghuang/codes/python/RLinf/logs/20260329-21:05:18/smolvla_40.pt # Optional: .pt file or None, if None, will use the checkpoint in rollout.model.model_path
  val_check_interval: -1
  save_interval: 10
  seq_length: 4096
  max_prompt_length: 50

  resume_dir: null # /home/bao_zonghuang/codes/python/RLinf/logs/20260430-12:33:13/test_smolvla/checkpoints/global_step_20

algorithm:
  normalize_advantages: True # True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  reward_coef: 1.0
  rollout_epoch: 4 # from 8 to 2
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: token_level

  update_epoch: 2
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean" 
  kl_beta:  0.0 # 0.0001 # ???
  entropy_bonus: 0 # 1e-4 # from 0 to 1e-4
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3
  value_clip: 0.2 # 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9
  # params for generation
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False # seamingly only support maniskill

  # Override the default values in env/libero_object
  train:
    task_suite_name: libero_1
    total_num_envs: 8 # from 64 to 8
    max_episode_steps: 520
    max_steps_per_rollout_epoch: 520
    use_fixed_reset_state_ids: True
    two_stage_reward: True
    reach_object_reward_coef: 0.05
    reach_object_reward_clip: 1.0
    place_target_reward_coef: 0.05
    place_target_reward_clip: 1.0
    reach_to_place_switch_dist: 0.04
    reward_probe_sim_state: True
  eval:
    task_suite_name: libero_object # libero_object_temp_x0.1
    total_num_envs: 10 # from 500 to 1
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 300 # from 240 to 300
    max_steps_per_rollout_epoch: 300 # from 240 to 300
    group_size: 1
    use_fixed_reset_state_ids: False
    is_eval: True
    use_recorded_init_state: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  generation_backend: "huggingface"
  recompute_logprobs: True
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/path/to/model/RLinf-Pi0-SFT-Spatial-Object-Goal"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  # from 128 to 4
  micro_batch_size: 16 # 4
  # from 2048 to 100 for aligning with reducing algorithem.rollout_epochs
  global_batch_size: 320 # must divide rollout_size (currently 8000) and be divisible by micro_batch_size
  # rollout_size = n_chunk_steps * rollout_epoch * total_env_nums
  seed: 42
  enable_offload: False
  idle_reserve_cuda_gb: 4 # 14
  idle_reserve_cuda_margin_gb: 1

  # Override the default values in model/smolvla
  model:
    model_path: "/path/to/model/RLinf-Pi0-SFT-Spatial-Object-Goal"
    model_type: "smolvla"
    precision: bf16
    num_action_chunks: 1 # interface for the env
    add_value_head: True
    is_lora: False
    # smolvla specific parameters
    smolvla:
      noise_method: "flow_cps"
      noise_level: 0.2
      detach_critic_input: True

  optim:
    lr: 4.0e-7 # 5.0e-6 # 4.0e-7: 等比缩小(并行环境 * rollout_epoch * micro_batch_size)
    value_lr: 8.0e-6 # 1.0e-4 # 8.0e-6
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    clip_grad: 1.0
    critic_warmup_steps: 200 # global steps
    # = warmup_epoches * update_epoch * rollout_size / batch_size_per_rank

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False # for openpi, gradient checkpointing is not supported, please do not change this value
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}
    use_orig_params: False

reward:
  use_reward_model: False

critic:
  use_critic_model: False